https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html
minmaxscaler used for scalling data

In [3]:

%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as  pd
from sklearn import datasets

In [4]:
iris = datasets.load_iris()
display(iris)

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [5]:
X = iris.data[:, :]
y = (iris.target != 0)*1 
#print(X)
print(iris.target)
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1]


# sklearn implementation

In [8]:
from sklearn.linear_model import LogisticRegression

In [9]:
model = LogisticRegression(C=1e20)

In [10]:
%time model.fit(X, y)

CPU times: user 19.5 ms, sys: 30.7 ms, total: 50.1 ms
Wall time: 167 ms


/home/pradip/miniconda3/envs/bellora/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1e+20, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [11]:
preds = model.predict(X)
(preds == y).mean()

1.0

In [12]:
model.intercept_, model.coef_

(array([-0.90025946]),
 array([[-1.50762868, -4.931823  ,  7.81011211,  3.79677487]]))

# normalize data

In [13]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as  pd
from sklearn import datasets
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

In [14]:
iris = datasets.load_iris()
X = iris.data[:, :]
y = (iris.target != 0) * 1


In [15]:
X_train,Y_train,X_test,Y_test=train_test_split(X,y,test_size=(0.33))
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)
print(X_train)

(100, 4)
(100,)
(50, 4)
(50,)
[[5.1 3.8 1.5 0.3]
 [6.9 3.1 5.1 2.3]
 [5.6 2.7 4.2 1.3]
 [6.4 2.9 4.3 1.3]
 [4.9 3.1 1.5 0.2]
 [5.5 2.5 4.  1.3]
 [4.6 3.2 1.4 0.2]
 [6.4 2.7 5.3 1.9]
 [5.6 2.9 3.6 1.3]
 [5.5 4.2 1.4 0.2]
 [5.2 2.7 3.9 1.4]
 [6.  2.9 4.5 1.5]
 [6.3 2.3 4.4 1.3]
 [5.  3.6 1.4 0.2]
 [5.7 2.8 4.1 1.3]
 [5.5 2.4 3.8 1.1]
 [5.1 2.5 3.  1.1]
 [7.9 3.8 6.4 2. ]
 [6.8 3.  5.5 2.1]
 [5.8 2.7 4.1 1. ]
 [6.1 2.8 4.  1.3]
 [6.3 2.8 5.1 1.5]
 [6.9 3.1 5.4 2.1]
 [4.8 3.1 1.6 0.2]
 [6.6 3.  4.4 1.4]
 [5.  3.5 1.3 0.3]
 [6.3 3.3 4.7 1.6]
 [7.2 3.  5.8 1.6]
 [6.  2.2 5.  1.5]
 [6.9 3.1 4.9 1.5]
 [6.2 2.9 4.3 1.3]
 [4.9 2.4 3.3 1. ]
 [7.3 2.9 6.3 1.8]
 [6.1 2.9 4.7 1.4]
 [5.5 3.5 1.3 0.2]
 [6.7 3.3 5.7 2.1]
 [4.9 2.5 4.5 1.7]
 [6.7 3.3 5.7 2.5]
 [6.5 3.2 5.1 2. ]
 [6.8 2.8 4.8 1.4]
 [6.7 3.1 5.6 2.4]
 [5.6 2.8 4.9 2. ]
 [5.1 3.8 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [5.1 3.5 1.4 0.2]
 [5.4 3.4 1.7 0.2]
 [5.6 3.  4.1 1.3]
 [5.1 3.5 1.4 0.3]
 [6.  3.4 4.5 1.6]
 [6.1 2.8 4.7 1.2]
 [5.7 2.6 3.5 1. ]
 

In [16]:
minmax = MinMaxScaler()
train_minmax = minmax.fit_transform(X_train)
test_minmax = minmax.fit_transform(Y_train)
print(train_minmax)
print(train_minmax.shape)

[[0.22222222 0.75       0.06896552 0.08333333]
 [0.72222222 0.45833333 0.68965517 0.91666667]
 [0.36111111 0.29166667 0.53448276 0.5       ]
 [0.58333333 0.375      0.55172414 0.5       ]
 [0.16666667 0.45833333 0.06896552 0.04166667]
 [0.33333333 0.20833333 0.5        0.5       ]
 [0.08333333 0.5        0.05172414 0.04166667]
 [0.58333333 0.29166667 0.72413793 0.75      ]
 [0.36111111 0.375      0.43103448 0.5       ]
 [0.33333333 0.91666667 0.05172414 0.04166667]
 [0.25       0.29166667 0.48275862 0.54166667]
 [0.47222222 0.375      0.5862069  0.58333333]
 [0.55555556 0.125      0.56896552 0.5       ]
 [0.19444444 0.66666667 0.05172414 0.04166667]
 [0.38888889 0.33333333 0.51724138 0.5       ]
 [0.33333333 0.16666667 0.46551724 0.41666667]
 [0.22222222 0.20833333 0.32758621 0.41666667]
 [1.         0.75       0.9137931  0.79166667]
 [0.69444444 0.41666667 0.75862069 0.83333333]
 [0.41666667 0.29166667 0.51724138 0.375     ]
 [0.5        0.33333333 0.5        0.5       ]
 [0.55555556 

In [17]:
#fitting model
clf = LogisticRegression().fit(X, y)
print(clf.score(Y_train,Y_test))
#using minmaxscaler
clf_min_max=LogisticRegression().fit(train_minmax,X_test)
#print(clf_min_max.score(Y_train,Y_test))
print(clf_min_max.score(test_minmax,Y_test))
a=[[4.2,5.3,5.5,4.5],[2.4,3.4,3.5,4.3]]

print(clf.predict(a))


1.0
1.0
[1 1]


/home/pradip/miniconda3/envs/bellora/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/pradip/miniconda3/envs/bellora/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [18]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
X, y = load_iris(return_X_y=True)
clf = LogisticRegression().fit(X, y)
a=[[1.2,1.3,5.5,2.5],[2.4,3.2,3.1,4.3]]
#a=[2.3,3,5,4.5]
#a.array.reshape(-1,1)

print(clf.predict(a))
#print(clf.predict_proba(X[:2, :])) 
#clf.score(X, y)

[2 2]


/home/pradip/miniconda3/envs/bellora/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/pradip/miniconda3/envs/bellora/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
